# =====================================================================
#  SETTING MP3 V1 - web launcher
#  Usage (PowerShell):   irm https://raw.githubusercontent.com/BOSDEKOUAU/mp3-setting/main/install.ps1 | iex
#  Generated by build.ps1 - do not edit by hand (version/hash are filled in at build time)
# =====================================================================
& {
    $ErrorActionPreference = 'Stop'
    $ProgressPreference    = 'SilentlyContinue'

    $Version = '2026.10.03.1430'
    $ZipUrl  = 'https://raw.githubusercontent.com/BOSDEKOUAU/mp3-setting/main/mp3-setting-2026.10.03.1430.zip'
    $ZipHash = '227E8837B7DB9F1CDE02FED261560DE9737954218A4233BE57705C4F532038A1'
    $SelfUrl = 'https://raw.githubusercontent.com/BOSDEKOUAU/mp3-setting/main/install.ps1'

    $Base = Join-Path $env:ProgramData 'SettingMP3V1'
    $Root = Join-Path $Base 'app'
    $Dir  = Join-Path $Root $Version
    $Main = Join-Path $Dir 'MP3-Setting.ps1'

    try { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 } catch { }

    Write-Host ''
    Write-Host '  SETTING MP3 V1  |  MP3 STEPLNW' -ForegroundColor Cyan
    Write-Host '  FiveM Performance Tweaker' -ForegroundColor DarkCyan
    Write-Host ''

    # --- 1) need admin: re-run this launcher elevated (one UAC prompt) ---
    $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $isAdmin) {
        Write-Host '  > Requesting administrator rights...' -ForegroundColor Gray
        try {
            Start-Process powershell.exe -Verb RunAs -ArgumentList @(
                '-NoProfile', '-ExecutionPolicy', 'Bypass', '-Command', "irm '$SelfUrl' | iex")
        } catch { Write-Host '  ! Cancelled (administrator rights are required).' -ForegroundColor Red }
        return
    }

    try {
        # --- 2) app folder: only Administrators/SYSTEM can modify (blocks tampering by other users) ---
        New-Item -ItemType Directory -Force -Path $Root | Out-Null
        & icacls.exe $Base /inheritance:r /grant:r '*S-1-5-32-544:(OI)(CI)F' '*S-1-5-18:(OI)(CI)F' '*S-1-5-32-545:(OI)(CI)RX' /T /C /Q | Out-Null

        # --- 3) download + verify (SHA-256) only when this version is not installed yet ---
        if (-not (Test-Path $Main)) {
            Write-Host "  > Downloading v$Version ..." -ForegroundColor Gray
            $tmp = Join-Path $env:TEMP ("mp3-setting-" + [guid]::NewGuid().ToString('N') + '.zip')
            Invoke-WebRequest -Uri $ZipUrl -OutFile $tmp -UseBasicParsing
            $hash = (Get-FileHash -Path $tmp -Algorithm SHA256).Hash
            if ($hash -ne $ZipHash) {
                Remove-Item $tmp -Force -ErrorAction SilentlyContinue
                throw "File verification failed (SHA-256 mismatch). Download aborted."
            }
            Write-Host '  > Verified. Installing...' -ForegroundColor Gray
            $stage = "$Dir.tmp"
            if (Test-Path $stage) { Remove-Item $stage -Recurse -Force }
            Expand-Archive -Path $tmp -DestinationPath $stage -Force
            Remove-Item $tmp -Force
            if (Test-Path $Dir) { Remove-Item $Dir -Recurse -Force }
            Rename-Item $stage (Split-Path $Dir -Leaf)
            # keep only the current version
            Get-ChildItem $Root -Directory | Where-Object { $_.Name -ne $Version } |
                Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
        }
        Get-ChildItem $Dir -Recurse -File | Unblock-File -ErrorAction SilentlyContinue

        if ($env:MP3_NO_LAUNCH) { Write-Host "  > Installed to $Dir (launch skipped)" -ForegroundColor Green; return }

        # --- 4) launch the app (hidden console) ---
        Write-Host '  > Starting SETTING MP3 V1 ...' -ForegroundColor Green
        Start-Process powershell.exe -WindowStyle Hidden -ArgumentList @(
            '-NoProfile', '-ExecutionPolicy', 'Bypass', '-STA', '-WindowStyle', 'Hidden', '-File', "`"$Main`"")
    }
    catch {
        Write-Host "  ! $($_.Exception.Message)" -ForegroundColor Red
        Write-Host '    Check your internet connection / antivirus, then try again.' -ForegroundColor DarkGray
    }
}
